name: rag_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - certifi=2024.12.14
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - comm=0.2.1
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - expat=2.6.2
  - fontconfig=2.14.1
  - freetype=2.12.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - ipykernel=6.28.0
  - ipython=8.25.0
  - ipywidgets=8.1.2
  - jedi=0.19.1
  - jinja2=3.1.4
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=3.0.10
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libpng=1.6.39
  - libpq=12.17
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.1
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mysql=5.7.24
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=7.0.8
  - notebook-shim=0.2.3
  - numexpr=2.10.1
  - numpy=2.1.3
  - numpy-base=2.1.3
  - openssl=3.0.15
  - overrides=7.4.0
  - packaging=24.1
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pip=24.2
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.12.4
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - qtconsole=5.5.1
  - qtpy=2.4.1
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - send2trash=1.8.2
  - setuptools=72.1.0
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tbb=2021.8.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - tzdata=2024a
  - urllib3=2.2.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - widgetsnbextension=4.0.10
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - alembic==1.14.0
      - annotated-types==0.7.0
      - blinker==1.9.0
      - cachetools==5.5.0
      - click==8.1.8
      - cloudpickle==3.1.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - databricks-sdk==0.40.0
      - deprecated==1.2.15
      - distro==1.9.0
      - docker==7.1.0
      - filelock==3.16.1
      - flask==3.1.0
      - fonttools==4.55.3
      - fsspec==2024.10.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.37.0
      - graphene==3.4.3
      - graphql-core==3.2.5
      - graphql-relay==3.2.0
      - greenlet==3.1.1
      - gunicorn==23.0.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.27.0
      - importlib-metadata==8.5.0
      - itsdangerous==2.2.0
      - jiter==0.8.2
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - mako==1.3.8
      - markdown==3.7
      - matplotlib==3.10.0
      - mlflow==2.19.0
      - mlflow-skinny==2.19.0
      - mpmath==1.3.0
      - networkx==3.4.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.59.6
      - opentelemetry-api==1.29.0
      - opentelemetry-sdk==1.29.0
      - opentelemetry-semantic-conventions==0.50b0
      - pillow==11.0.0
      - protobuf==5.29.3
      - pyarrow==18.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pyparsing==3.2.0
      - regex==2024.11.6
      - rsa==4.9
      - safetensors==0.4.5
      - scikit-learn==1.6.0
      - scipy==1.14.1
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - smmap==5.0.2
      - sqlalchemy==2.0.37
      - sqlparse==0.5.3
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - tiktoken==0.8.0
      - tokenizers==0.21.0
      - torch==2.5.1
      - tqdm==4.67.1
      - transformers==4.48.0
      - triton==3.1.0
      - typing-extensions==4.12.2
      - werkzeug==3.1.3
      - wrapt==1.17.1
      - zipp==3.21.0
