from setuptools import setup, find_packages


setup(
    name="workmind",
    version="0.1.0",
    author="Vlad Kisin",
    description="Framework for HR-related sentiment analysis and interventions generation",
    packages=find_packages(),
    install_requires=[
        "torch",
        "scikit-learn",
        "pandas",
        "numpy",
        "matplotlib",
        "seaborn",
        "wandb",
        "tqdm",
        "nltk",
        "transformers",
        "datasets",
        "sentence_transformers",
        "accelerate",
        "peft",
        "bitsandbytes",
        "adapters",
        "trl",
        "adapter-transformers",
        "PyMuPDF",
        "bert_score",
        "evaluate",
        "readability",
        "rouge_score",
        "llama-index",
        "llama-index-llms-huggingface",
        "llama-index-embeddings-huggingface",
        "llama-index-retrievers-bm25",
    ],
    python_requires=">=3.8",
)
